version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout

      - run: sudo apt-get -y install g++ build-essential make autoconf libglfw3-dev libsdl2-image-dev libsdl2-dev libczmq-dev

      - run:
          name: Execute Makefile
          working_directory: Project
          command: make -j 4

      - run:
          name: Run test demo
          working_directory: Project
          command: ./MeshGlide -debug -playdemo citest.demo

workflows:
  main:
    jobs:
      - build
